### ISSUE TITLE
--comment => -c

### ISSUE THREAD

**Issue by tomryanx** [equalitie/edgemanage#13]
allow --comment to be abbreviated as -c

**Comment by tomryanx** [comment]
might be an idea to add other abbreviations, eg for "-m" to have "a" "ua" "f" and "bf"

**Comment by nosmo** [comment]
-c is currently standardised as shorthand for "--config" in edge_manage, edge_conf, edge_query.

**Comment by tomryanx** [comment]
Hmmm.  Good point.  Could we change --config to --file with -f for short?

**Comment by nosmo** [comment]
fwiw -C is a shorthand for comment. Given that it's somewhat established that -c is for config across all scripts I am somewhat loath to change it.

**Comment by tomryanx** [comment]
should have closed myself a while ago. all good!
