### ISSUE TITLE
Upload v2.0.7 to PyPI

### ISSUE THREAD

**Issue by graphiclunarkid** [equalitie/edgemanage#27]
We just released Edgemanage 2.0.7 and should push this to PyPI. I believe @nosmo is the only person who can do this, since it seems to require an account, which I'm assuming he controls...

**Comment by nosmo** [comment]
I'll try to both upload the newest version and also transfer ownership tonight

**Comment by graphiclunarkid** [comment]
Two things:

1. I pushed a 1-line update to INSTALL.md today as I forgot to update it when I reorganised the repo.
2. We're still doing some testing to make double sure this version is OK.

If you could transfer the ownership that'd be great, as then we won't keep bugging you for updates in future, but maybe hold off pushing this version to PyPI until we confirm it's fine?

**Comment by nosmo** [comment]
👍

**Comment by graphiclunarkid** [comment]
@RamJett confirms all is good. Fire at will :smile: :shipit:

**Comment by nosmo** [comment]
New version uploaded! Still trying to figure out how to transfer ownership, if ye have any pointers please let me know

**Comment by nosmo** [comment]
oh, just found it - if the suitable parties create pypi accounts and email me their usernames I can do the necessaries

**Comment by graphiclunarkid** [comment]
@nosmo I've created a pypi account with username "equalitie".

**Comment by nosmo** [comment]
Done!

**Comment by graphiclunarkid** [comment]
Thanks!
